

build: nftp-bridge/target/wasm32-unknown-unknown/release/near_nftp_bridge.wasm

nftp-bridge/target/wasm32-unknown-unknown/release/near_nftp_bridge.wasm: nftp-bridge/src/*.rs  nftp-bridge/Cargo.toml
	cd nftp-bridge; cargo build --target wasm32-unknown-unknown --release

