[features]
seeds = true 
skip-lint = false
[programs.localnet]
nftp = "EdPCWzayyrWEzFLAjkaVjKivGcSVRKJYdcT7Uqf2bTxd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ben/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
